cadmin:
  security:
    mode: local

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.security.oauth2.client.autoconfigure.reactive.ReactiveOAuth2ClientWebSecurityAutoConfiguration
  devtools:
    restart:
      enabled: true
    add-properties: true
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
